version = "0.1.0"
author = "LinksPlatform contributors"
description = "Swappable native and GraphQL Doublets API"
license = "Unlicense"
srcDir = "src"
requires "nim >= 2.0.0"
requires "platform_data_doublets_native >= 0.1.0"
requires "platform_data_doublets_gql_client >= 0.1.0"
